
#pragma once

#if defined(QTSCORE_LIBRARY)
#  define QTSCORE_EXPORT Q_DECL_EXPORT
#else
#  define QTSCORE_EXPORT Q_DECL_IMPORT
#endif

#define QT_QTSINGLECOREAPPLICATION_EXPORT QTSCORE_EXPORT
#define QT_QTSERVICE_EXPORT               QTSCORE_EXPORT
#define QT_QTLOCKEDFILE_EXPORT            QTSCORE_EXPORT
