
#pragma once

#if defined(QTSGUI_LIBRARY)
#  define QTSGUI_EXPORT Q_DECL_EXPORT
#else
#  define QTSGUI_EXPORT Q_DECL_IMPORT
#endif

#define QT_QTPROPERTYBROWSER_EXPORT   QTSGUI_EXPORT
#define QT_QTSINGLEAPPLICATION_EXPORT QTSGUI_EXPORT
