#ifndef CTCOINCODES_H
#define CTCOINCODES_H

#include <QHash>
#include <QMultiHash>
#include <QList>
#include <QPair>

struct SCoinByCode
{
  public:

    typedef QList<const char*> Countries;

    SCoinByCode()
      : realCode(0), code(nullptr), name(nullptr) {}
    SCoinByCode(quint16 r, const char* c, const char* n, const Countries& cts)
      : realCode(r), code(c), name(n), countries(cts) {}

    quint16     realCode;
    const char* code;
    const char* name;
    Countries   countries;
};

const struct SCoinCodes
{
  public:

    SCoinCodes():
      coinById {
          {"AED", QPair<quint16, quint8>(784, 0x10)},
          {"AFN", QPair<quint16, quint8>(971, 0xCB)},
          {"ALL", QPair<quint16, quint8>(  8, 0x08)},
          {"AMD", QPair<quint16, quint8>( 51, 0x33)},
          {"ANG", QPair<quint16, quint8>(532, 0x14)},
          {"AOA", QPair<quint16, quint8>(973, 0xCD)},
          {"ARS", QPair<quint16, quint8>( 32, 0x20)},
          {"AUD", QPair<quint16, quint8>( 36, 0x24)},
          {"AWG", QPair<quint16, quint8>(533, 0x15)},
          {"AZN", QPair<quint16, quint8>(944, 0xB0)},
          {"BAM", QPair<quint16, quint8>(977, 0xD1)},
          {"BBD", QPair<quint16, quint8>( 52, 0x34)},
          {"BDT", QPair<quint16, quint8>( 50, 0x32)},
          {"BGN", QPair<quint16, quint8>(975, 0xCF)},
          {"BHD", QPair<quint16, quint8>( 48, 0x30)},
          {"BIF", QPair<quint16, quint8>(108, 0x6C)},
          {"BMD", QPair<quint16, quint8>( 60, 0x3C)},
          {"BND", QPair<quint16, quint8>( 96, 0x60)},
          {"BOB", QPair<quint16, quint8>( 68, 0x44)},
          {"BRL", QPair<quint16, quint8>(986, 0xDA)},
          {"BSD", QPair<quint16, quint8>( 44, 0x2C)},
          {"BTN", QPair<quint16, quint8>( 64, 0x40)},
          {"BWP", QPair<quint16, quint8>( 72, 0x48)},
          {"BYN", QPair<quint16, quint8>(933, 0xA5)},
          {"BZD", QPair<quint16, quint8>( 84, 0x54)},
          {"CAD", QPair<quint16, quint8>(124, 0x7C)},
          {"CDF", QPair<quint16, quint8>(976, 0xD0)},
          {"CHF", QPair<quint16, quint8>(756, 0xF4)},
          {"CLP", QPair<quint16, quint8>(152, 0x98)},
          {"CNY", QPair<quint16, quint8>(156, 0x9C)},
          {"COP", QPair<quint16, quint8>(170, 0xAA)},
          {"CRC", QPair<quint16, quint8>(188, 0xBC)},
          {"CUC", QPair<quint16, quint8>(931, 0xA3)},
          {"CUP", QPair<quint16, quint8>(192, 0xC0)},
          {"CVE", QPair<quint16, quint8>(132, 0x84)},
          {"CZK", QPair<quint16, quint8>(203, 0xCB)},
          {"DJF", QPair<quint16, quint8>(262, 0x06)},
          {"DKK", QPair<quint16, quint8>(208, 0xD0)},
          {"DOP", QPair<quint16, quint8>(214, 0xD6)},
          {"DZD", QPair<quint16, quint8>(012, 0x0C)},
          {"EGP", QPair<quint16, quint8>(818, 0x32)},
          {"ERN", QPair<quint16, quint8>(232, 0xE8)},
          {"ETB", QPair<quint16, quint8>(230, 0xE6)},
          {"EUR", QPair<quint16, quint8>(978, 0xD2)},
          {"FJD", QPair<quint16, quint8>(242, 0xF2)},
          {"FKP", QPair<quint16, quint8>(238, 0xEE)},
          {"GBP", QPair<quint16, quint8>(826, 0x3A)},
          {"GEL", QPair<quint16, quint8>(981, 0xD5)},
          {"GHS", QPair<quint16, quint8>(936, 0xA8)},
          {"GIP", QPair<quint16, quint8>(292, 0x24)},
          {"GMD", QPair<quint16, quint8>(270, 0x0E)},
          {"GNF", QPair<quint16, quint8>(324, 0x44)},
          {"GTQ", QPair<quint16, quint8>(320, 0x40)},
          {"GYD", QPair<quint16, quint8>(328, 0x48)},
          {"HKD", QPair<quint16, quint8>(344, 0x58)},
          {"HNL", QPair<quint16, quint8>(340, 0x54)},
          {"HRK", QPair<quint16, quint8>(191, 0xBF)},
          {"HTG", QPair<quint16, quint8>(332, 0x4C)},
          {"HUF", QPair<quint16, quint8>(348, 0x5C)},
          {"IDR", QPair<quint16, quint8>(360, 0x68)},
          {"ILS", QPair<quint16, quint8>(376, 0x78)},
          {"INR", QPair<quint16, quint8>(356, 0x64)},
          {"IQD", QPair<quint16, quint8>(368, 0x70)},
          {"IRR", QPair<quint16, quint8>(364, 0x6C)},
          {"ISK", QPair<quint16, quint8>(352, 0x60)},
          {"JMD", QPair<quint16, quint8>(388, 0x84)},
          {"JOD", QPair<quint16, quint8>(400, 0x90)},
          {"JPY", QPair<quint16, quint8>(392, 0x88)},
          {"KES", QPair<quint16, quint8>(404, 0x94)},
          {"KGS", QPair<quint16, quint8>(417, 0xA1)},
          {"KHR", QPair<quint16, quint8>(116, 0x74)},
          {"KMF", QPair<quint16, quint8>(174, 0xAE)},
          {"KPW", QPair<quint16, quint8>(408, 0x98)},
          {"KRW", QPair<quint16, quint8>(410, 0x9A)},
          {"KWD", QPair<quint16, quint8>(414, 0x9E)},
          {"KYD", QPair<quint16, quint8>(136, 0x88)},
          {"KZT", QPair<quint16, quint8>(398, 0x8E)},
          {"LAK", QPair<quint16, quint8>(418, 0xA2)},
          {"LBP", QPair<quint16, quint8>(422, 0xA6)},
          {"LKR", QPair<quint16, quint8>(144, 0x90)},
          {"LRD", QPair<quint16, quint8>(430, 0xAE)},
          {"LSL", QPair<quint16, quint8>(426, 0xAA)},
          {"LYD", QPair<quint16, quint8>(434, 0xB2)},
          {"MAD", QPair<quint16, quint8>(504, 0xF8)},
          {"MDL", QPair<quint16, quint8>(498, 0xF2)},
          {"MGA", QPair<quint16, quint8>(969, 0xC9)},
          {"MKD", QPair<quint16, quint8>(807, 0x27)},
          {"MMK", QPair<quint16, quint8>(104, 0x68)},
          {"MNT", QPair<quint16, quint8>(496, 0xF0)},
          {"MOP", QPair<quint16, quint8>(446, 0xBE)},
          {"MRO", QPair<quint16, quint8>(478, 0xDE)},
          {"MUR", QPair<quint16, quint8>(480, 0xE0)},
          {"MVR", QPair<quint16, quint8>(462, 0xCE)},
          {"MWK", QPair<quint16, quint8>(454, 0xC6)},
          {"MXN", QPair<quint16, quint8>(484, 0xE4)},
          {"MYR", QPair<quint16, quint8>(458, 0xCA)},
          {"MZN", QPair<quint16, quint8>(943, 0xAF)},
          {"NAD", QPair<quint16, quint8>(516, 0x04)},
          {"NGN", QPair<quint16, quint8>(566, 0x36)},
          {"NIO", QPair<quint16, quint8>(558, 0x2E)},
          {"NOK", QPair<quint16, quint8>(578, 0x42)},
          {"NPR", QPair<quint16, quint8>(524, 0x0C)},
          {"NZD", QPair<quint16, quint8>(554, 0x2A)},
          {"OMR", QPair<quint16, quint8>(512, 0x00)},
          {"PAB", QPair<quint16, quint8>(590, 0x4E)},
          {"PEN", QPair<quint16, quint8>(604, 0x5C)},
          {"PGK", QPair<quint16, quint8>(598, 0x56)},
          {"PHP", QPair<quint16, quint8>(608, 0x60)},
          {"PKR", QPair<quint16, quint8>(586, 0x4A)},
          {"PLN", QPair<quint16, quint8>(985, 0xD9)},
          {"PYG", QPair<quint16, quint8>(600, 0x58)},
          {"QAR", QPair<quint16, quint8>(634, 0x7A)},
          {"RON", QPair<quint16, quint8>(946, 0xB2)},
          {"RSD", QPair<quint16, quint8>(941, 0xAD)},
          {"RUB", QPair<quint16, quint8>(643, 0x83)},
          {"RWF", QPair<quint16, quint8>(646, 0x86)},
          {"SAR", QPair<quint16, quint8>(682, 0xAA)},
          {"SBD", QPair<quint16, quint8>( 90, 0x5A)},
          {"SCR", QPair<quint16, quint8>(690, 0xB2)},
          {"SDG", QPair<quint16, quint8>(938, 0xAA)},
          {"SEK", QPair<quint16, quint8>(752, 0xF0)},
          {"SGD", QPair<quint16, quint8>(702, 0xBE)},
          {"SHP", QPair<quint16, quint8>(654, 0x8E)},
          {"SLL", QPair<quint16, quint8>(694, 0xB6)},
          {"SOS", QPair<quint16, quint8>(706, 0xC2)},
          {"SRD", QPair<quint16, quint8>(968, 0xC8)},
          {"SSP", QPair<quint16, quint8>(728, 0xD8)},
          {"STD", QPair<quint16, quint8>(678, 0xA6)},
          {"SVC", QPair<quint16, quint8>(222, 0xDE)},
          {"SYP", QPair<quint16, quint8>(760, 0xF8)},
          {"SZL", QPair<quint16, quint8>(748, 0xEC)},
          {"THB", QPair<quint16, quint8>(764, 0xFC)},
          {"TJS", QPair<quint16, quint8>(972, 0xCC)},
          {"TMT", QPair<quint16, quint8>(934, 0xA6)},
          {"TND", QPair<quint16, quint8>(788, 0x14)},
          {"TOP", QPair<quint16, quint8>(776, 0x08)},
          {"TRY", QPair<quint16, quint8>(949, 0xB5)},
          {"TTD", QPair<quint16, quint8>(780, 0x0C)},
          {"TWD", QPair<quint16, quint8>(901, 0x85)},
          {"TZS", QPair<quint16, quint8>(834, 0x42)},
          {"UAH", QPair<quint16, quint8>(980, 0xD4)},
          {"UGX", QPair<quint16, quint8>(800, 0x20)},
          {"USD", QPair<quint16, quint8>(840, 0x48)},
          {"UYU", QPair<quint16, quint8>(858, 0x5A)},
          {"UZS", QPair<quint16, quint8>(860, 0x5C)},
          {"VEF", QPair<quint16, quint8>(937, 0xA9)},
          {"VND", QPair<quint16, quint8>(704, 0xC0)},
          {"VUV", QPair<quint16, quint8>(548, 0x24)},
          {"WST", QPair<quint16, quint8>(882, 0x72)},
          {"XAF", QPair<quint16, quint8>(950, 0xB6)},
          {"XCD", QPair<quint16, quint8>(951, 0xB7)},
          {"XOF", QPair<quint16, quint8>(952, 0xB8)},
          {"XPF", QPair<quint16, quint8>(953, 0xB9)},
          {"XSU", QPair<quint16, quint8>(994, 0xE2)},
          {"YER", QPair<quint16, quint8>(886, 0x76)},
          {"ZAR", QPair<quint16, quint8>(710, 0xC6)},
          {"ZMW", QPair<quint16, quint8>(967, 0xC7)},
          {"ZWL", QPair<quint16, quint8>(932, 0xA4)},
        },
      coinByCode {
    {0x00, SCoinByCode(512, "OMR", "Rial"       , {"Oman"})},
    {0x04, SCoinByCode(516, "NAD", "Dollar"     , {"Namibia"})},
    {0x06, SCoinByCode(262, "DJF", "Franc"      , {"Djibouti"})},
    {0x08, SCoinByCode(  8, "ALL", "Lek"        , {"Albania"})},
    {0x08, SCoinByCode(776, "TOP", "Paʻanga"    , {"Tonga"})},
    {0x0C, SCoinByCode(780, "TTD", "Dollar"     , {"Trinidad and Tobago"})},
    {0x0C, SCoinByCode(012, "DZD", "Dinar"      , {"Algeria"})},
    {0x0C, SCoinByCode(524, "NPR", "Rupee"      , {"Nepal"})},
    {0x0E, SCoinByCode(270, "GMD", "Dalasi"     , {"Gambia"})},
    {0x10, SCoinByCode(784, "AED", "Dirham"     , {"United Arab Emirates"})},
    {0x14, SCoinByCode(532, "ANG", "Guilder"    , {"Curaçao", "Sint Maarten"})},
    {0x14, SCoinByCode(788, "TND", "Dinar"      , {"Tunisia"})},
    {0x15, SCoinByCode(533, "AWG", "Florin"     , {"Aruba"})},
    {0x20, SCoinByCode( 32, "ARS", "Peso"       , {"Argentina"})},
    {0x20, SCoinByCode(800, "UGX", "Shilling"   , {"Uganda"})},
    {0x24, SCoinByCode(548, "VUV", "Vatu"       , {"Vanuatu"})},
    {0x24, SCoinByCode( 36, "AUD", "Dollar"     , {"Australia", "Christmas Island", "Cocos Islands", "Heard Island and McDonald Islands", "Kiribati", "Nauru", "Norfolk Island", "Tuvalu"})},
    {0x24, SCoinByCode(292, "GIP", "Pound"      , {"Gibraltar"})},
    {0x27, SCoinByCode(807, "MKD", "Denar"      , {"Macedonia"})},
    {0x2A, SCoinByCode(554, "NZD", "Dollar"     , {"New Zealand", "Cook Islands", "Niue", "Pitcairn Islands", "Tokelau"})},
    {0x2C, SCoinByCode( 44, "BSD", "Dollar"     , {"Bahamas"})},
    {0x2E, SCoinByCode(558, "NIO", "Córdoba"    , {"Nicaragua"})},
    {0x30, SCoinByCode( 48, "BHD", "Dinar"      , {"Bahrain"})},
    {0x32, SCoinByCode(818, "EGP", "Pound"      , {"Egypt"})},
    {0x32, SCoinByCode( 50, "BDT", "Taka"       , {"Bangladesh"})},
    {0x33, SCoinByCode( 51, "AMD", "Dram"       , {"Armenia"})},
    {0x34, SCoinByCode( 52, "BBD", "Dollar"     , {"Barbados"})},
    {0x36, SCoinByCode(566, "NGN", "Naira"      , {"Nigeria"})},
    {0x3C, SCoinByCode( 60, "BMD", "Dollar"     , {"Bermuda"})},
    {0x3A, SCoinByCode(826, "GBP", "Sterling"   , {"United Kingdom", "The  Isle of Man", "Jersey", "Guernsey"})},
    {0x40, SCoinByCode( 64, "BTN", "Ngultrum"   , {"Bhutan"})},
    {0x40, SCoinByCode(320, "GTQ", "Quetzal"    , {"Guatemala"})},
    {0x42, SCoinByCode(834, "TZS", "Shilling"   , {"Tanzania"})},
    {0x42, SCoinByCode(578, "NOK", "Krone"      , {"Norway", "Svalbard and Jan Mayen", "Bouvet Island"})},
    {0x44, SCoinByCode( 68, "BOB", "Boliviano"  , {"Bolivia"})},
    {0x44, SCoinByCode(324, "GNF", "Franc"      , {"Guinea"})},
    {0x48, SCoinByCode( 72, "BWP", "Pula"       , {"Botswana"})},
    {0x48, SCoinByCode(328, "GYD", "Dollar"     , {"Guyana"})},
    {0x48, SCoinByCode(840, "USD", "Dollar"     , {"United States", "American Samoa", "Barbados", "Bermuda", "British Indian Ocean Territory", "British Virgin Islands", "Caribbean Netherlands", "Ecuador", "El Salvador", "Guam", "Haiti", "Marshall Islands", "Federated States of Micronesia", "Northern Mariana Islands", "Palau", "Panama", "Puerto Rico", "Timor-Leste", "Turks and Caicos Islands", "U.S. Virgin Islands", "United States Minor Outlying Islands"})},
    {0x4A, SCoinByCode(586, "PKR", "Rupee"      , {"Pakistan"})},
    {0x4C, SCoinByCode(332, "HTG", "Gourde"     , {"Haiti"})},
    {0x4E, SCoinByCode(590, "PAB", "Balboa"     , {"Panama"})},
    {0x54, SCoinByCode( 84, "BZD", "Dollar"     , {"Belize"})},
    {0x54, SCoinByCode(340, "HNL", "Lempira"    , {"Honduras"})},
    {0x56, SCoinByCode(598, "PGK", "Kina"       , {"Papua New Guinea"})},
    {0x58, SCoinByCode(600, "PYG", "Guaraní"    , {"Paraguay"})},
    {0x58, SCoinByCode(344, "HKD", "Dollar"     , {"Hong Kong"})},
    {0x5A, SCoinByCode( 90, "SBD", "Dollar"     , {"Solomon Islands"})},
    {0x5A, SCoinByCode(858, "UYU", "Peso"       , {"Uruguay"})},
    {0x5C, SCoinByCode(860, "UZS", "Som"        , {"Uzbekistan"})},
    {0x5C, SCoinByCode(348, "HUF", "Forint"     , {"Hungary"})},
    {0x5C, SCoinByCode(604, "PEN", "Sol"        , {"Peru"})},
    {0x60, SCoinByCode(352, "ISK", "Króna"      , {"Iceland"})},
    {0x60, SCoinByCode( 96, "BND", "Dollar"     , {"Brunei"})},
    {0x60, SCoinByCode(608, "PHP", "Peso"       , {"Philippines"})},
    {0x64, SCoinByCode(356, "INR", "Rupee"      , {"India", "Bhutan"})},
    {0x68, SCoinByCode(104, "MMK", "Kyat"       , {"Myanmar"})},
    {0x68, SCoinByCode(360, "IDR", "Rupiah"     , {"Indonesia"})},
    {0x6C, SCoinByCode(364, "IRR", "Rial"       , {"Iran"})},
    {0x6C, SCoinByCode(108, "BIF", "Franc"      , {"Burundi"})},
    {0x70, SCoinByCode(368, "IQD", "Dinar"      , {"Iraq"})},
    {0x72, SCoinByCode(882, "WST", "Tala"       , {"Samoa"})},
    {0x74, SCoinByCode(116, "KHR", "Riel"       , {"Cambodia"})},
    {0x76, SCoinByCode(886, "YER", "Rial"       , {"Yemen"})},
    {0x78, SCoinByCode(376, "ILS", "Shekel"     , {"Israel"})},
    {0x7A, SCoinByCode(634, "QAR", "Riyal"      , {"Qatar"})},
    {0x7C, SCoinByCode(124, "CAD", "Dollar"     , {"Canada"})},
    {0x83, SCoinByCode(643, "RUB", "Ruble"      , {"Russia"})},
    {0x84, SCoinByCode(132, "CVE", "Escudo"     , {"Cape Verde"})},
    {0x84, SCoinByCode(388, "JMD", "Dollar"     , {"Jamaica"})},
    {0x85, SCoinByCode(901, "TWD", "Dollar"     , {"Taiwan"})},
    {0x86, SCoinByCode(646, "RWF", "Franc"      , {"Rwanda"})},
    {0x88, SCoinByCode(392, "JPY", "Yen"        , {"Japan"})},
    {0x88, SCoinByCode(136, "KYD", "Dollar"     , {"Cayman Islands"})},
    {0x8E, SCoinByCode(398, "KZT", "Tenge"      , {"Kazakhstan"})},
    {0x8E, SCoinByCode(654, "SHP", "Pound"      , {"Saint Helena", "Ascension Island", "Tristan da Cunha"})},
    {0x90, SCoinByCode(144, "LKR", "Rupee"      , {"Sri Lanka"})},
    {0x90, SCoinByCode(400, "JOD", "Dinar"      , {"Jordan"})},
    {0x94, SCoinByCode(404, "KES", "Shilling"   , {"Kenya"})},
    {0x98, SCoinByCode(408, "KPW", "Won"        , {"North Korea"})},
    {0x98, SCoinByCode(152, "CLP", "Peso"       , {"Chile"})},
    {0x9A, SCoinByCode(410, "KRW", "Won"        , {"South Korea"})},
    {0x9C, SCoinByCode(156, "CNY", "Yuan"       , {"China"})},
    {0x9E, SCoinByCode(414, "KWD", "Dinar"      , {"Kuwait"})},
    {0xA1, SCoinByCode(417, "KGS", "Som"        , {"Kyrgyzstan"})},
    {0xA2, SCoinByCode(418, "LAK", "Kip"        , {"Laos"})},
    {0xA3, SCoinByCode(931, "CUC", "Peso"       , {"Cuba"})},
    {0xA4, SCoinByCode(932, "ZWL", "Dollar"     , {"Zimbabwe"})},
    {0xA5, SCoinByCode(933, "BYN", "Ruble"      , {"Belarus"})},
    {0xA6, SCoinByCode(934, "TMT", "Manat"      , {"Turkmenistan"})},
    {0xA6, SCoinByCode(678, "STD", "Dobra"      , {"São Tomé and Príncipe"})},
    {0xA6, SCoinByCode(422, "LBP", "Pound"      , {"Lebanon"})},
    {0xA8, SCoinByCode(936, "GHS", "Cedi"       , {"Ghana"})},
    {0xA9, SCoinByCode(937, "VEF", "Bolívar"    , {"Venezuela"})},
    {0xAA, SCoinByCode(938, "SDG", "Pound"      , {"Sudan"})},
    {0xAA, SCoinByCode(682, "SAR", "Riyal"      , {"Saudi Arabia"})},
    {0xAA, SCoinByCode(170, "COP", "Peso"       , {"Colombia"})},
    {0xAA, SCoinByCode(426, "LSL", "Loti"       , {"Lesotho"})},
    {0xAD, SCoinByCode(941, "RSD", "Dinar"      , {"Serbia"})},
    {0xAE, SCoinByCode(174, "KMF", "Franc"      , {"Comoros"})},
    {0xAE, SCoinByCode(430, "LRD", "Dollar"     , {"Liberia"})},
    {0xAF, SCoinByCode(943, "MZN", "Metical"    , {"Mozambique"})},
    {0xB0, SCoinByCode(944, "AZN", "Manat"      , {"Azerbaijan"})},
    {0xB2, SCoinByCode(690, "SCR", "Rupee"      , {"Seychelles"})},
    {0xB2, SCoinByCode(434, "LYD", "Dinar"      , {"Libya"})},
    {0xB2, SCoinByCode(946, "RON", "Leu"        , {"Romania"})},
    {0xB5, SCoinByCode(949, "TRY", "Lira"       , {"Turkey"})},
    {0xB6, SCoinByCode(950, "XAF", "Franc"      , {"Cameroon", "Central African Republic", "Republic of the Congo", "Chad", "Equatorial Guinea", "Gabon"})},
    {0xB6, SCoinByCode(694, "SLL", "Leone"      , {"Sierra Leone"})},
    {0xB7, SCoinByCode(951, "XCD", "Dollar"     , {"Anguilla", "Antigua and Barbuda", "Dominica", "Grenada", "Montserrat", "Saint Kitts and Nevis", "Saint Lucia", "Saint Vincent and the Grenadines"})},
    {0xB8, SCoinByCode(952, "XOF", "Franc"      , {"Benin", "Burkina Faso", "Côte d'Ivoire", "Guinea-Bissau", "Mali", "Niger", "Senegal", "Togo"})},
    {0xB9, SCoinByCode(953, "XPF", "Franc"      , {"French Polynesia", "New Caledonia", "Wallis and Futuna"})},
    {0xBC, SCoinByCode(188, "CRC", "Colon"      , {"Costa Rica"})},
    {0xBE, SCoinByCode(702, "SGD", "Dollar"     , {"Singapore"})},
    {0xBE, SCoinByCode(446, "MOP", "Pataca"     , {"Macao"})},
    {0xBF, SCoinByCode(191, "HRK", "Kuna"       , {"Croatia"})},
    {0xC0, SCoinByCode(192, "CUP", "Peso"       , {"Cuba"})},
    {0xC0, SCoinByCode(704, "VND", "đồng"       , {"Vietnam"})},
    {0xC2, SCoinByCode(706, "SOS", "Shilling"   , {"Somalia"})},
    {0xC6, SCoinByCode(710, "ZAR", "Rand"       , {"South Africa"})},
    {0xC6, SCoinByCode(454, "MWK", "Kwacha"     , {"Malawi"})},
    {0xC7, SCoinByCode(967, "ZMW", "Kwacha"     , {"Zambia"})},
    {0xC8, SCoinByCode(968, "SRD", "Dollar"     , {"Suriname"})},
    {0xC9, SCoinByCode(969, "MGA", "Ariary"     , {"Madagascar"})},
    {0xCA, SCoinByCode(458, "MYR", "Ringgit"    , {"Malaysia"})},
    {0xCB, SCoinByCode(203, "CZK", "Koruna"     , {"Czech Republic"})},
    {0xCB, SCoinByCode(971, "AFN", "Afghani"    , {"Afghanistan"})},
    {0xCC, SCoinByCode(972, "TJS", "Somoni"     , {"Tajikistan"})},
    {0xCD, SCoinByCode(973, "AOA", "Kwanza"     , {"Angola"})},
    {0xCE, SCoinByCode(462, "MVR", "Rufiyaa"    , {"Maldives"})},
    {0xCF, SCoinByCode(975, "BGN", "Lev"        , {"Bulgaria"})},
    {0xD0, SCoinByCode(976, "CDF", "Franc"      , {"Democratic Republic of the Congo"})},
    {0xD0, SCoinByCode(208, "DKK", "Krone"      , {"Denmark", "Faroe Islands", "Greenland"})},
    {0xD1, SCoinByCode(977, "BAM", "Mark"       , {"Bosnia and Herzegovina"})},
    {0xD2, SCoinByCode(978, "EUR", "Euro"       , {"Andorra", "Austria", "Belgium", "Cyprus", "Estonia", "Finland", "France", "Germany", "Greece", "Guadeloupe", "Ireland", "Italy", "Latvia", "Lithuania", "Luxembourg", "Malta", "Martinique", "Mayotte", "Monaco", "Montenegro", "Netherlands", "Portugal", "Réunion", "Saint Barthélemy", "Saint Pierre and Miquelon", "San Marino", "Slovakia", "Slovenia", "Spain"})},
    {0xD5, SCoinByCode(981, "GEL", "Lari"       , {"Georgia"})},
    {0xD6, SCoinByCode(214, "DOP", "Peso"       , {"Dominican Republic"})},
    {0xD4, SCoinByCode(980, "UAH", "Hryvnia"    , {"Ukraine"})},
    {0xD8, SCoinByCode(728, "SSP", "Pound"      , {"South Sudan"})},
    {0xD9, SCoinByCode(985, "PLN", "Złoty"      , {"Poland"})},
    {0xDA, SCoinByCode(986, "BRL", "Real"       , {"Brazil"})},
    {0xDE, SCoinByCode(222, "SVC", "Colón"      , {"El Salvador"})},
    {0xDE, SCoinByCode(478, "MRO", "Ouguiya"    , {"Mauritania"})},
    {0xE0, SCoinByCode(480, "MUR", "Rupee"      , {"Mauritius"})},
    {0xE2, SCoinByCode(994, "XSU", "SUCRE"      , {"Unified System for Regional Compensation"})},
    {0xE4, SCoinByCode(484, "MXN", "Peso"       , {"Mexico"})},
    {0xE6, SCoinByCode(230, "ETB", "Birr"       , {"Ethiopia"})},
    {0xE8, SCoinByCode(232, "ERN", "Nakfa"      , {"Eritrea"})},
    {0xEC, SCoinByCode(748, "SZL", "Lilangeni"  , {"Swaziland"})},
    {0xEE, SCoinByCode(238, "FKP", "Pound"      , {"Falkland Islands"})},
    {0xF0, SCoinByCode(752, "SEK", "Krona"      , {"Sweden"})},
    {0xF0, SCoinByCode(496, "MNT", "Tögrög"     , {"Mongolia"})},
    {0xF2, SCoinByCode(498, "MDL", "Leu"        , {"Moldova"})},
    {0xF2, SCoinByCode(242, "FJD", "Dollar"     , {"Fiji"})},
    {0xF4, SCoinByCode(756, "CHF", "Franc"      , {"Switzerland", "Liechtenstein"})},
    {0xF8, SCoinByCode(760, "SYP", "Pound"      , {"Syria"})},
    {0xF8, SCoinByCode(504, "MAD", "Dirham"     , {"Morocco"})},
    {0xFC, SCoinByCode(764, "THB", "Baht"       , {"Thailand"})},
      }
    { }

    SCoinByCode operator[](quint8 id) const
    { return coinByCode.values(id).last(); }

    SCoinByCode operator[](const char* name) const
    { return operator [](coinById.value(name).second); }

  private:
    QHash<const char*, QPair<quint16, quint8> > coinById;
    QMultiHash<quint8, SCoinByCode>             coinByCode;

} coinCodes;

#endif // CTCOINCODES_H
